apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: monitoring-grafana
spec:
  rules:
  - host: heapster.vungle.io
    http:
      paths:
      - path: /
        backend:
          serviceName: monitoring-grafana
          servicePort: 80

