apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    k8s-app: heapster
    name: heapster
    version: v6
  name: heapster
  namespace: prod
spec:
  replicas: 1
  selector:
    k8s-app: heapster
    version: v6
  template:
    metadata:
      labels:
        k8s-app: heapster
        version: v6
    spec:
      containers:
      - command:
        - /heapster
        - --source=kubernetes:https://kubernetes.default.svc
        #- --sink=influxdb:http://influx-udp.default.svc.cluster.local:8086
        - --sink=kafka:?brokers=kafka.prod.svc.cluster.local:9092&timeseriestopic=inf-heapster-metrics&eventstopic=inf-heapster-events
        #- --sink=log
        image: kubernetes/heapster:canary
        imagePullPolicy: Always
        name: heapster
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  fullyLabeledReplicas: 1
  observedGeneration: 1
  replicas: 1
